// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy2QRpyiW0uBCN9qE4EdAZGq1wUrwNhSU',
    appId: '1:939034290081:web:961d145eb93a4f28978de0',
    messagingSenderId: '939034290081',
    projectId: 'crud-22344',
    authDomain: 'crud-22344.firebaseapp.com',
    storageBucket: 'crud-22344.appspot.com',
    measurementId: 'G-JYQNPR4FSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQpZV5KrlditL39-PbqkraQe9s1WesY9s',
    appId: '1:939034290081:android:106e631c6c4d4b3f978de0',
    messagingSenderId: '939034290081',
    projectId: 'crud-22344',
    storageBucket: 'crud-22344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbD3R0tL8NCsb-3Iv4NvayXPmNooYhIIQ',
    appId: '1:939034290081:ios:149e9321f0ab7368978de0',
    messagingSenderId: '939034290081',
    projectId: 'crud-22344',
    storageBucket: 'crud-22344.appspot.com',
    androidClientId: '939034290081-8qf0pma5o3aectb4upmutnhp1i7tsgi9.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
